// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35NmePXo5cnZEeetT1E1F5RW2LO7xO5A',
    appId: '1:946021198705:web:2da83a2d02f31260c9e4d0',
    messagingSenderId: '946021198705',
    projectId: 'promoteuganda-f8261',
    authDomain: 'promoteuganda-f8261.firebaseapp.com',
    storageBucket: 'promoteuganda-f8261.appspot.com',
    measurementId: 'G-JWPQGM5FRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_9mCnhBEXSSSabXeADbNehoisBx9XQ4',
    appId: '1:946021198705:android:0f98b32cc2e9f67dc9e4d0',
    messagingSenderId: '946021198705',
    projectId: 'promoteuganda-f8261',
    storageBucket: 'promoteuganda-f8261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xkYB7Ug88lnU2XuNvUyEsk8AP0ZiJcI',
    appId: '1:946021198705:ios:936c9796594eb777c9e4d0',
    messagingSenderId: '946021198705',
    projectId: 'promoteuganda-f8261',
    storageBucket: 'promoteuganda-f8261.appspot.com',
    iosClientId: '946021198705-p17qlc0am7obv2fj935f2ke8fne71qvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.promoteUganda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7xkYB7Ug88lnU2XuNvUyEsk8AP0ZiJcI',
    appId: '1:946021198705:ios:8c543646964d5ad5c9e4d0',
    messagingSenderId: '946021198705',
    projectId: 'promoteuganda-f8261',
    storageBucket: 'promoteuganda-f8261.appspot.com',
    iosClientId: '946021198705-o1qaa6k8dkcgmns2o9pr3dmsu1p72201.apps.googleusercontent.com',
    iosBundleId: 'com.example.promoteUganda.RunnerTests',
  );
}
